#!/bin/bash
MAILTO=maxhalford25@gmail.com

*/2 * * * * cd /var/www/api.openbikes.co && /home/axel/anaconda3/envs/openbikes/bin/python manage.py fetchdocks ALL 3
*/15 * * * * cd /var/www/api.openbikes.co && /home/axel/anaconda3/envs/openbikes/bin/python manage.py fetchweather ALL 3
